apiVersion: v1
kind: Service
metadata:
  name: customer-ms
  namespace: bookstore-ns
spec:
  type: LoadBalancer
  selector:
    app: customer-ms
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
