apiVersion: v1
kind: Service
metadata:
  name: book-ms
  namespace: bookstore-ns
spec:
  type: LoadBalancer
  selector:
    app: book-ms
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
