apiVersion: v1
kind: Service
metadata:
  name: web-bff
  namespace: bookstore-ns
spec:
  type: LoadBalancer
  selector:
    app: web-bff
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
