apiVersion: v1
kind: Service
metadata:
  name: crm-ms
  namespace: bookstore-ns
spec:
  type: LoadBalancer
  selector:
    app: crm-ms
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
